# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Enzyme Design
tagline:          Software Development and Managed Services
url:              http://thinkenzyme.com
paginate:         1
baseurl:          /
